### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by BiohazzardXIII** [ethical42/idle-miner#1]
Hello,

Thank you for making this amazing code. I do have 1 suggestion though, it is possible to only execute the Hunt and fish command every 5 minutes. If you could implement that or message me with insight into where to put extra code that would be great.

Thank you

**Comment by ethical42** [comment]
Hey,

This should work, modify time as you wish: 
[fish-hunt.py.zip](https://github.com/ethical42/idle-miner/files/7696107/fish-hunt.py.zip)
